### ISSUE TITLE
Error message for only one single root spin state

### ISSUE THREAD

**Issue by nagb** [YoshioNishimoto/Some-Developments-with-OpenMolcas#5]
[test-triplet.zip](https://github.com/YoshioNishimoto/Some-Developments-with-OpenMolcas/files/6593350/test-triplet.zip)

Optimising a triplet with a CAS(2,2) seems to run into an error in the property section both with and without the SADREF key.

The singlets run ok.

--
 ###############################################################################
 ###############################################################################
 ###                                                                         ###
 ###                                                                         ###
 ###    Location: AixRd                                                      ###
 ###    File: LUCIEX                                                         ###
 ###                                                                         ###
 ###                                                                         ###
 ###    Premature abort while reading buffer from disk                       ###
 ###    End of file reached                                                  ###
 ###                                                                         ###
 ###                                                                         ###
 ###############################################################################
 ###############################################################################
--- Stop Module: caspt2 at Thu Jun  3 07:53:52 2021 /rc=_RC_IO_ERROR_READ_ ---

**Comment by YoshioNishimoto** [comment]
Thank you for the report. I hope the patch added in the develop branch will fix the problem. Please note that triplet states with CAS(2e,2o) wavefunction are equivalent to the corresponding RO-HF solution. The number of CSF is only one, and it can be a special case for post-CASSCF treatments.

**Comment by nagb** [comment]
Thanks for the patch! 

I'll re-run it again and let you know how it goes.

By the way you should declare or allocate the variable idSDMat in file clagx.f (subroutine CLagDX) otherwise the Intel Fortran compiler will terminate linking with an error message:

ld: CMakeFiles/caspt2.dir/src/caspt2/clagx.f.o: in function `clagdx_':
clagx.f:(.text+0x3d03): undefined reference to `idsdmat_'

**Comment by nagb** [comment]
I can confirm the issue is now gone and the optimisation proceeds as expected.

**Comment by YoshioNishimoto** [comment]
I'm relieved to know that it is working. It seems that I forgot updating caspt2_grad.fh, when I committed some time. This caused the compiler issue. Maybe only diagonal CASPT2 gradients have been working...
